name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to trigger the workflow on

env:
  IMAGE_NAME: devsecops-demo
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz
        tar zxvf trivy_0.20.0_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/
    
    - name: Scan Docker image
      id: trivy_scan
      run: |
        trivy --exit-code 1 --no-progress --format json --output trivy_report.json docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Upload scan report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy_report.json

    - name: Build Docker image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

    - name: Push Docker image
      run: docker push docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
